name: 'Manual Merge Test'
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  merge:
    name: Merge the PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: l10n_main
      - run: echo "Pull Request ${number} (${sha})"
        env:
          number: '${{ steps.find-pull-request.outputs.number }}'
          sha: '${{ steps.find-pull-request.outputs.head-sha }}'
      - name: Merge Pull Request
        if: steps.find-pull-request.outputs.number != 0
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          number: '${{ steps.find-pull-request.outputs.number }}'
          method: squash
          repo: '${{ github.repository }}'
