name: 'Manual Test'
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  publish:
    name: Build Resource Pack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Fetch Latest Minecraft Release
        id: fetch-mc-release
        run: |
          curl -o minecraft.json https://piston-meta.mojang.com/mc/game/version_manifest_v2.json && echo ::set-output name=minecraftVersion::$(cat minecraft.json)
      - name: Print
        run: echo "${{ fromJson(steps.fetch-mc-release.outputs.minecraftVersion).latest.release }}"
